-----
title: "Assignment1_DL_mmarjan1"
author: "Marianne Marjanovic"
date: "February 17, 2019"
output: html_document
-----


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)

library(keras)
```


#  LOADING THE DATA:

```{r}
imdb <- dataset_imdb(num_words = 10000)
c(c(train_data, train_labels), c(test_data, test_labels)) %<-% imdb

```


###  ENCODING THE DATA:

```{r}

vectorize_sequences <- function(sequences, dimension = 10000) {

    # Create an all-zero matrix of shape (len(sequences), dimension)
  results <- matrix(0, nrow = length(sequences), ncol = dimension)
  for (i in 1:length(sequences))

    # Sets specific indices of results[i] to 1s
    results[i, sequences[[i]]] <- 1
  results
}


# Our vectorized training data
x_train <- vectorize_sequences(train_data)

# Our vectorized test data
x_test <- vectorize_sequences(test_data)


# Our vectorized labels
y_train <- as.numeric(train_labels)
y_test <- as.numeric(test_labels)

```



#  BUILDING THE MODEL:

```{r}
 
l1_l2_model <- keras_model_sequential() %>% 
  layer_dense(units = 16, kernel_regularizer = regularizer_l1_l2(l1 = 0.01, l2 =   0.01),
              activation = "relu", input_shape = c(10000)) %>% 

  layer_dense(units = 16, kernel_regularizer = regularizer_l1_l2(l1 = 0.01, l2 = 0.01),
              activation = "relu") %>% 

  layer_dense(units = 1, activation = "sigmoid")


### COMPILING THE MODEL:

l1_l2_model %>% compile(
  optimizer = "rmsprop",
  loss = "binary_crossentropy",
  metrics = c("acc")

)

```

#  TRAINING THE MODEL:

```{r, echo=TRUE, results='hide'}

l1_l2_model_hist <- l1_l2_model %>% fit(
  x_train, y_train,
  epochs = 20,
  batch_size = 512,
  validation_data = list(x_test, y_test)

)

results <- l1_l2_model %>% evaluate(x_test, y_test)

```


#  THE RESULTS:

```{r}

results

```



