---
title: "SA"
author: "Marianne Marjanovic"
date: "November 7, 2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r, eval = TRUE}
knitr::opts_chunk$set(echo = TRUE)

#Load Libraries
install.packages('GenSA')
install.packages("GA")
install.packages("quantmod")
library('ggplot2')
library('quantmod')
library('GA')
library('GenSA')

```


Problem 1

```{r}
#Feeding real-time stock data into the system

tickers <- c("F", "MCD", "NKE", "TGT", "GIS")
getSymbols(tickers, from = "2008-12-01", to = "2018-10-31", src =  "yahoo", adjust =  TRUE)

P <- NULL
for(ticker in tickers) {
 tmp <- Cl(to.monthly(eval(parse(text = ticker))))
 P <- cbind(P, tmp)
}
colnames(P) <- tickers
R <- diff(log(P))
R <- R[-1,]
mu <- colMeans(R)
sigma <- cov(R)
library("PerformanceAnalytics")
pContribCVaR <- ES(weights = rep(0.2, 5), method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)$pct_contrib_ES
obj <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out <- tmp1 - 1e+3 * tmp2
 return(out)
}
obj1 <- function(w) {
 fn.call <<- fn.call + 1
 if (sum(w) == 0) { w <- w + 1e-2 }
 w <- w / sum(w)
 CVaR <- ES(weights = w, method = "gaussian", portfolio_method = "component", mu = mu, sigma = sigma)
 tmp1 <- CVaR$ES
 tmp2 <- max(CVaR$pct_contrib_ES - 0.225, 0)
 out1 <- tmp1 + 1e+3 * tmp2
 return(out1)
}
```


```{r}
#Applying GA to assign weights for optimum portfolio using min objective
# Where x1 = BAC, x2 = F, x3 = GE, x4 = AAPL and x5 = WMT
# Solution is the weights assigned to each of the stocks for optimum portfolio
set.seed(1234)
fn.call <<- 0
gap <- ga(type = "real-valued",fitness=obj,lower=rep(0,5),upper=rep(1,5), popSize = 50,maxiter = 150, pcrossover = 0.75, pmutation = 0.1)
nsol <- gap@solution
nsol <- nsol / sum(nsol)
fn.call.gap <- fn.call
nsol
summary(gap)
plot(gap)
```

```{r}
#Applying GenSA to assign weights to the stocks for optimum portfolio using max objective
set.seed(1234)
fn.call <<- 0
out.GenSA <- GenSA(fn = obj1, lower = rep(0, 5), upper = rep(1, 5), control = list(smooth = FALSE, max.call = 3000))
fn.call.GenSA <- fn.call
out.GenSA$value
out.GenSA$counts
cat("GenSA call functions", fn.call.GenSA, "times.\n")
wstar.GenSA <- out.GenSA$par
wstar.GenSA <- wstar.GenSA / sum(wstar.GenSA)
rbind(tickers, round(100 * wstar.GenSA, 2))
100 * (sum(wstar.GenSA * mu) - mean(mu))
wstar.GenSA


```

```{r}
#comparing the weights as per both the algorithms
b <- matrix(c(nsol, wstar.GenSA), nrow = 5, ncol = 2)
rownames(b) = c("F", "MCD", "NKE", "TGT", "GIS")
colnames(b) = c("GAPortfolio", "GenSAPortfolio")
b

TickerSymbol <- (c("F","MCD","NKE","TGT","GIS","______","TOTAL"))
Company <- (c("Ford","McDonalds","Nike","Target","General Mills","",""))
GA_percent  <- (c(11,21,19,18,31,"_____ ",100))
GenSA_percent <- (c(6,31,18,17,28,"_____ ",100))
TData <- data.frame(TickerSymbol, Company, GA_percent, GenSA_percent) 
TData



```






Problem 2

```{r cars}
X <- (c(25,8,9,19,34,46,72,39,3,10,61,82,14,20,52,49,62,55,30,33))
Y <- (c(25,43,14,18,84,61,2,34,91,28,73,47,19,82,72,65,80,71,24,30))
data2 <- data.frame(X,Y)

lm(formula = Y ~ X)

p <- ggplot(data=data2,aes(X,Y)) + geom_point()
p <- p + stat_smooth(method = "lm", aes(color="Linear Regression"),
        se = FALSE,
        size = 1) +
  scale_color_manual(name="Legend",values= c("Linear Regression"="#C42126")) + ggtitle("Line Plots")
p




```


